# Generated by Django 5.1.5 on 2026-03-28 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='attractions/')),
                ('tab', models.CharField(choices=[('highlights', 'Highlights'), ('cities', 'Cities'), ('unesco', 'UNESCO Heritage'), ('culture', 'Culture'), ('regions', 'Regions'), ('culinary', 'Culinary')], max_length=20)),
                ('badge', models.CharField(choices=[('city', 'City'), ('nature', 'Nature'), ('unesco', 'UNESCO'), ('sport', 'Sport'), ('relax-and-wellness', 'Relax and Wellness'), ('culture', 'Culture'), ('culinary', 'Culinary'), ('region', 'Region')], max_length=30)),
                ('card_size', models.CharField(choices=[('card-tall', 'Tall'), ('card-almost-tall', 'Almost Tall'), ('card-short', 'Short')], default='card-short', max_length=20)),
                ('column', models.IntegerField(choices=[(1, 'Column 1'), (2, 'Column 2'), (3, 'Column 3')], default=1)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['column', 'order'],
            },
        ),
    ]
