# Generated by Django 5.1.5 on 2026-04-05 14:19

import tourism.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0002_attraction'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attraction',
            options={'ordering': ['column', 'order'], 'verbose_name': 'Attraction', 'verbose_name_plural': 'Get Insipred (Home)'},
        ),
        migrations.AlterModelOptions(
            name='carouselitem',
            options={'ordering': ['order'], 'verbose_name': 'Carousel Item', 'verbose_name_plural': 'Carousel (Home)'},
        ),
        migrations.AlterField(
            model_name='attraction',
            name='image',
            field=models.ImageField(upload_to=tourism.models.attraction_upload_path),
        ),
    ]
