# Generated by Django 5.1.5 on 2026-04-08 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0003_alter_attraction_options_alter_carouselitem_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('show_see_all', models.BooleanField(default=True)),
                ('see_all_text', models.CharField(blank=True, max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Tabs',
                'ordering': ['order'],
            },
        ),
        migrations.AlterField(
            model_name='attraction',
            name='tab',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attractions', to='tourism.tab'),
        ),
    ]
