# Generated by Django 5.1.5 on 2026-04-08 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0004_tab_alter_attraction_tab'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attraction',
            name='tab',
            field=models.CharField(choices=[('highlights', 'Highlights'), ('cities', 'Cities'), ('unesco', 'UNESCO Heritage'), ('culture', 'Culture'), ('regions', 'Regions'), ('culinary', 'Culinary')], max_length=20),
        ),
        migrations.DeleteModel(
            name='Tab',
        ),
    ]
