# Generated by Django 5.1.5 on 2026-04-11 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0005_alter_attraction_tab_delete_tab'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('show_see_all', models.BooleanField(default=True)),
                ('see_all_text', models.CharField(blank=True, max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Tab',
                'verbose_name_plural': 'Tabs',
                'ordering': ['order'],
            },
        ),
    ]
