# Generated by Django 5.1.5 on 2026-04-11 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0006_tab'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attraction',
            options={'ordering': ['column', 'order'], 'verbose_name': 'Attraction', 'verbose_name_plural': 'Get Inspired (Home)'},
        ),
        migrations.AlterField(
            model_name='attraction',
            name='tab',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attractions', to='tourism.tab'),
        ),
    ]
