# Generated by Django 5.1.5 on 2026-04-11 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0007_alter_attraction_options_alter_attraction_tab'),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('color', models.CharField(default='#343b7b', max_length=7)),
            ],
            options={
                'verbose_name': 'Badge',
                'verbose_name_plural': 'Badges',
            },
        ),
        migrations.AlterModelOptions(
            name='tab',
            options={'ordering': ['order'], 'verbose_name': 'Tab', 'verbose_name_plural': 'Tabs (Get Inspired/Home)'},
        ),
        migrations.AlterField(
            model_name='attraction',
            name='badge',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attractions', to='tourism.badge'),
        ),
    ]
