# Generated by Django 5.1.5 on 2026-04-11 14:08

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0008_badge_alter_tab_options_alter_attraction_badge'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='badge',
            options={'verbose_name': 'Badge', 'verbose_name_plural': 'Badges (Get Inspired/Home)'},
        ),
        migrations.AlterField(
            model_name='badge',
            name='color',
            field=colorfield.fields.ColorField(default='#5d646b', image_field=None, max_length=25, samples=None),
        ),
    ]
