# Generated by Django 5.1.5 on 2026-04-28 13:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0011_favourite'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='favourite',
            constraint=models.UniqueConstraint(fields=('user', 'attraction'), name='unique_user_attraction_favourite'),
        ),
        migrations.AddConstraint(
            model_name='favourite',
            constraint=models.UniqueConstraint(fields=('user', 'tour'), name='unique_user_tour_favourite'),
        ),
        migrations.AddConstraint(
            model_name='favourite',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('attraction__isnull', False), ('tour__isnull', True)), models.Q(('attraction__isnull', True), ('tour__isnull', False)), _connector='OR'), name='favourite_exactly_one_item'),
        ),
    ]
