# Generated by Django 5.1.5 on 2026-05-24 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0012_favourite_unique_user_attraction_favourite_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attraction',
            name='tab',
        ),
        migrations.CreateModel(
            name='AttractionTab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column', models.IntegerField(choices=[(1, 'Column 1'), (2, 'Column 2'), (3, 'Column 3')], default=1)),
                ('order', models.PositiveIntegerField(default=0)),
                ('attraction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tourism.attraction')),
                ('tab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tourism.tab')),
            ],
            options={
                'ordering': ['column', 'order'],
                'unique_together': {('attraction', 'tab')},
            },
        ),
        migrations.AddField(
            model_name='attraction',
            name='tabs',
            field=models.ManyToManyField(related_name='attractions', through='tourism.AttractionTab', to='tourism.tab'),
        ),
    ]
