# Generated by Django 5.1.5 on 2026-05-24 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0013_remove_attraction_tab_attractiontab_attraction_tabs'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attraction',
            options={'verbose_name': 'Attraction', 'verbose_name_plural': 'Get Inspired (Home)'},
        ),
        migrations.RemoveField(
            model_name='attraction',
            name='column',
        ),
        migrations.RemoveField(
            model_name='attraction',
            name='order',
        ),
    ]
