# Generated by Django 5.1.5 on 2026-05-31 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0014_alter_attraction_options_remove_attraction_column_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favourite',
            options={'ordering': ['created_at'], 'verbose_name_plural': 'Favourites'},
        ),
    ]
