# Generated by Django 5.1.5 on 2026-06-04 12:37

import tourism.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0015_alter_favourite_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attraction',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=tourism.models.attraction_upload_path),
        ),
    ]
