# Generated by Django 5.1.5 on 2026-06-06 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0016_alter_attraction_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='tours/'),
        ),
    ]
